# Generated by Django 5.1 on 2024-08-25 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=2000)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sp", "Strictly Platonic"),
                            ("ww", "Women seeking Women"),
                            ("wm", "Women seeking Men"),
                            ("mw", "Men seeking Women"),
                            ("mm", "Men seeking Men"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            (0, "Alabama"),
                            (1, "Alaska"),
                            (2, "Arizona"),
                            (3, "Arkansas"),
                            (4, "California"),
                            (5, "Colorado"),
                            (6, "Connecticut"),
                            (7, "Delaware"),
                            (8, "Florida"),
                            (9, "Georgia"),
                            (10, "Hawaii"),
                            (11, "Idaho"),
                            (12, "Illinois"),
                            (13, "Indian"),
                            (14, "Iowa"),
                            (15, "Kansas"),
                            (16, "Kentucky"),
                            (17, "Louisiana"),
                            (18, "Maine"),
                            (19, "Maryland"),
                            (20, "Massachusetts"),
                            (21, "Michigan"),
                            (22, "Minnesota"),
                            (23, "Mississippi"),
                            (24, "Missouri"),
                            (25, "Montana"),
                            (26, "Nebraska"),
                            (27, "Nevada"),
                            (28, "New Hampshire"),
                            (29, "New Jersey"),
                            (30, "New Mexico"),
                            (31, "New York"),
                            (32, "North Carolina"),
                            (33, "North Dakota"),
                            (34, "Ohio"),
                            (35, "Oklahoma"),
                            (36, "Oregon"),
                            (37, "Pennsylvania"),
                            (38, "Rhode Island"),
                            (39, "South Carolina"),
                            (40, "South Dakota"),
                            (41, "Tennessee"),
                            (42, "Texas"),
                            (43, "Utah"),
                            (44, "Vermont"),
                            (45, "Virginia"),
                            (46, "Washington"),
                            (47, "West Virginia"),
                            (48, "Wisconsin"),
                            (49, "Wyoming"),
                            (50, "Ontario"),
                            (51, "Quebec"),
                            (52, "Nova Scotia"),
                            (53, "New Brunswick"),
                            (54, "Manitoba"),
                            (55, "British Columbia"),
                            (56, "Prince Edward Island"),
                            (57, "Saskatchewan"),
                            (58, "Alberta"),
                            (59, "Newfoundland and Labrador"),
                        ],
                        max_length=2,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("favorites", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "poster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("tags", models.ManyToManyField(to="ads.tags")),
            ],
        ),
    ]
