# Generated by Django 5.1 on 2024-08-26 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0004_alter_ad_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ad",
            name="favorites",
        ),
        migrations.AddField(
            model_name="ad",
            name="flags",
            field=models.ManyToManyField(
                blank=True, related_name="flagged_ads", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
