# Generated by Django 5.1 on 2024-08-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0005_remove_ad_favorites_ad_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ad",
            name="payment_status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
