# Generated by Django 5.1 on 2024-08-28 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0007_remove_ad_payment_id_remove_ad_payment_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="ad_p",
            new_name="linked_ad",
        ),
    ]
